### ISSUE TITLE
Use Egyptian Brackets

### ISSUE THREAD

**Issue by MrGallo** [IPalaganas/pbd-solutions#1]
Please use Egyptian-brackets in your code.

**Meh:**
```java
public static void main(String[] args)
{
    System.out.println("Hello");
}
```

**Much Better:**
```java
public static void main(String[] args) {
    System.out.println("Hello");
}
```
See [Number 3](https://blog.codinghorror.com/new-programming-jargon/)

**Comment by IPalaganas** [comment]
okay ill use egyptian brackets from 09 onwards.
